import { useEffect, useState } from 'react'
import { acceptBindRequest, getInviteCodes, rejectBindRequest } from '../../api/coach'
import type { CoachBindRequest, InviteCode } from '../../api/types'
import { kg, profileLine, shortDate, techniqueStyleLine } from './WorkspaceCommon'

export function RequestsPage({ requests, onRequestsChanged, onAccepted }: { requests: CoachBindRequest[]; onRequestsChanged: (rows: CoachBindRequest[]) => void; onAccepted: () => void | Promise<void> }) {
  const [open, setOpen] = useState<Set<string>>(new Set()), [busy, setBusy] = useState(''), [codes, setCodes] = useState<InviteCode[]>([]), [copied, setCopied] = useState(false)
  useEffect(() => { void getInviteCodes().then(setCodes).catch(() => setCodes([])) }, [])
  const personal = codes.find((c) => c.type === 'personal_permanent' && !c.revoked_at) ?? codes.find((c) => !c.revoked_at)
  const remove = (id: string) => onRequestsChanged(requests.filter((r) => r.id !== id))
  const accept = async (r: CoachBindRequest) => { setBusy(r.id); try { await acceptBindRequest(r.id); remove(r.id); await onAccepted() } finally { setBusy('') } }
  const reject = async (r: CoachBindRequest) => { if (!window.confirm(`拒绝 ${r.display_name} 的申请？`)) return; setBusy(r.id); try { await rejectBindRequest(r.id); remove(r.id) } finally { setBusy('') } }
  return <main className="data-page requests-page"><header className="page-top"><span className="page-eyebrow">COACH / 学员申请</span><span className="page-spacer" /><span className="page-status">● {requests.length} 待处理 · 60s 自动刷新</span></header><div className="request-list">{requests.length === 0 && <div className="empty-state">暂无待处理申请</div>}{requests.map((r) => { const p = r.onboarding, expanded = open.has(r.id); return <section key={r.id}><div className="request-row" onClick={() => setOpen((prev) => { const next = new Set(prev); if (next.has(r.id)) next.delete(r.id); else next.add(r.id); return next })}><span className="avatar">{r.display_name.slice(0, 1)}</span><span className="request-who"><b>{r.display_name}</b><small>{r.masked_phone || '手机号未提供'} · {new Date(r.submitted_at).toLocaleString('zh-CN')} · 邀请码 {r.invite_code || '—'}</small></span><span>{expanded ? '收起 ▲' : '展开 ▼'}</span><button disabled={busy === r.id} onClick={(e) => { e.stopPropagation(); void reject(r) }}>拒绝</button><button className="accept" disabled={busy === r.id} onClick={(e) => { e.stopPropagation(); void accept(r) }}>{busy === r.id ? '处理中…' : '接受'}</button></div>{expanded && <div className="request-detail"><h3>ONBOARDING · 学员自填</h3><div><span><small>基础</small><b>{profileLine(p)}</b></span><span><small>训练年限</small><b>{p.training_years != null ? `${p.training_years} 年 · 每周 ${p.training_days?.length ?? '—'} 天` : '未填写'}</b></span><span><small>自报 1RM</small><b>S {kg(p.squat_1rm_kg)} / B {kg(p.bench_1rm_kg)} / D {kg(p.deadlift_1rm_kg)}</b></span><span><small>技术风格</small><b>{techniqueStyleLine(p)}</b></span><span><small>伤病</small><b>{p.injury_notes || p.injury_areas?.join('、') || '无'}</b></span><span><small>备赛</small><b>{p.is_competing ? `${shortDate(p.competition_date)} · ${p.target_weight_class || '未填级别'}` : '暂不备赛'}</b></span></div>{p.note_to_coach && <blockquote>“{p.note_to_coach}”</blockquote>}</div>}</section> })}</div><footer className="invite-footer"><span>我的邀请码</span><b>{personal?.code ?? '暂无可用邀请码'}</b><button disabled={!personal} onClick={() => { if (!personal) return; void navigator.clipboard.writeText(personal.code); setCopied(true); window.setTimeout(() => setCopied(false), 1600) }}>{copied ? '已复制' : '复制'}</button></footer></main>
}
